version: "3.5"
services:
  redis_master:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - redis-replication-net
  redis_slave:
    image: redis:latest
    command: redis-server --slaveof redis_master 6379
    ports:
      - "6380:6379"
    networks:
      - redis-replication-net
    depends_on:
      - redis_master

networks:
    redis-replication-net: 
