version: "3.5"
services:
  master:
    image: mysql:5.7
    command: mysqld  --log_bin=mysql-bin --server_id=10
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - "3308:3306"
    networks:
      - mysql-replication
  slave:
    image: mysql:5.7
    command: mysqld --log_bin=mysql-bin --server_id=11 --log_slave_updates=1 --read_only=1 
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - "3309:3306"
    networks:
      - mysql-replication
  replication-init:
    build: ./replication-init
    networks:
      - mysql-replication

networks:
  mysql-replication: 

