# 注意，需要在hosts文件中配置中增加一行：127.0.0.1 mongo1 mongo2 mongo3
version: "3.5"
services:
    mongo1:
        image: mongo:4.0
        command: mongod --bind_ip_all --replSet rs --port 37017
        ports:
            - "37017:37017"
        networks: 
            - mongo-rs
    mongo2:
        image: mongo:4.0
        command: mongod --bind_ip_all --replSet rs --port 37018
        ports:
            - "37018:37018"
        networks: 
            - mongo-rs
    mongo3:
        image: mongo:4.0
        command: mongod --bind_ip_all --replSet rs --port 37019
        ports:
            - "37019:37019"
        networks: 
            - mongo-rs


networks:
    mongo-rs:
