version: "3.5"
services:
  redis1:
    build:
      context: .
      dockerfile: cluster-dockerfile
    command: "/usr/local/bin/redis-server /root/cluster.conf --port 6379"
    ports:
      - "6379:6379"

  redis2:
    build:
      context: .
      dockerfile: cluster-dockerfile
    command: "/usr/local/bin/redis-server /root/cluster.conf --port 6380"
    ports:
      - "6380:6380"
 
  redis3:
    build:
      context: .
      dockerfile: cluster-dockerfile
    command: "/usr/local/bin/redis-server /root/cluster.conf --port 6381"
    ports:
      - "6381:6381"
 
  redis4:
    build:
      context: .
      dockerfile: cluster-dockerfile
    command: "/usr/local/bin/redis-server /root/cluster.conf --port 6382"
    ports:
      - "6382:6382"
 
 

  redis5:
    build:
      context: .
      dockerfile: cluster-dockerfile
    command: "/usr/local/bin/redis-server /root/cluster.conf --port 6383"
    ports:
      - "6383:6383"

  redis6:
    build:
      context: .
      dockerfile: cluster-dockerfile
    command: "/usr/local/bin/redis-server /root/cluster.conf --port 6384"
    ports:
      - "6384:6384"
 
